=== sseuniverse/sse-hooks/schema/meta.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the item. This is used to identify the item in the registry. It should be unique for your registry."
    },
    "type": {
      "type": "string",
      "enum": ["registry:hook"],
      "description": "The type of the item. This is used to determine the type and target path of the item when resolved for a project."
    },
    "description": {
      "type": "string",
      "description": "The description of the item. This is used to provide a brief overview of the item."
    },
    "title": {
      "type": "string",
      "description": "The human-readable title for your registry item. Keep it short and descriptive."
    },
    "dependencies": {
      "type": "array",
      "description": "An array of NPM dependencies required by the registry item.",
      "items": {
        "type": "string"
      }
    },
    "registryDependencies": {
      "type": "array",
      "description": "An array of SSE Hooks required by the registry item.",
      "items": {
        "type": "string"
      }
    },
    "file": {
      "type": "object",
      "description": "The file information for the registry item.",
      "properties": {
        "path": {
          "type": "string",
          "description": "The path where the file should be placed when the registry item is resolved."
        },
        "content": {
          "type": "string",
          "description": "The content of the file."
        },
        "js": {
          "type": "string",
          "description": "The JavaScript code of the file."
        }
      },
      "required": ["content", "js"]
    }
  }
}

=== sseuniverse/sse-hooks/packages/hooks/src/useIntersectionObserver/meta.json
{
  "$schema": "https://raw.githubusercontent.com/sseuniverse/sse-hooks/refs/heads/main/schema/meta.json",
  "name": "use-intersection-observer",
  "type": "registry:hook",
  "title": "useIntersectionObserver",
  "description": "The hook internal state.",
  "dependencies": [
    "react"
  ],
  "registryDependencies": [],
  "file": {
    "content": "import { useEffect, useRef, useState } from \"react\";\r\n\r\n\r\ntype State = {\r\n  \r\n  isIntersecting: boolean;\r\n  \r\n  entry?: IntersectionObserverEntry;\r\n};\r\n\r\n\r\ntype UseIntersectionObserverOptions = {\r\n  \r\n  root?: Element | Document | null;\r\n  \r\n  rootMargin?: string;\r\n  \r\n  threshold?: number | number[];\r\n  \r\n  freezeOnceVisible?: boolean;\r\n  \r\n  onChange?: (\r\n    isIntersecting: boolean,\r\n    entry: IntersectionObserverEntry,\r\n  ) => void;\r\n  \r\n  initialIsIntersecting?: boolean;\r\n};\r\n\r\n\r\ntype IntersectionReturn = [\r\n  (node?: Element | null) => void,\r\n  boolean,\r\n  IntersectionObserverEntry | undefined,\r\n] & {\r\n  ref: (node?: Element | null) => void;\r\n  isIntersecting: boolean;\r\n  entry?: IntersectionObserverEntry;\r\n};\r\n\r\n\r\nexport function useIntersectionObserver({\r\n  threshold = 0,\r\n  root = null,\r\n  rootMargin = \"0%\",\r\n  freezeOnceVisible = false,\r\n  initialIsIntersecting = false,\r\n  onChange,\r\n}: UseIntersectionObserverOptions = {}): IntersectionReturn {\r\n  const [ref, setRef] = useState<Element | null>(null);\r\n\r\n  const [state, setState] = useState<State>(() => ({\r\n    isIntersecting: initialIsIntersecting,\r\n    entry: undefined,\r\n  }));\r\n\r\n  \r\n  const callbackRef = useRef<UseIntersectionObserverOptions[\"onChange\"]>();\r\n\r\n  callbackRef.current = onChange;\r\n\r\n  const frozen = state.entry?.isIntersecting && freezeOnceVisible;\r\n\r\n  useEffect(() => {\r\n    \r\n    if (!ref) return;\r\n\r\n    \r\n    if (!(\"IntersectionObserver\" in window)) return;\r\n\r\n    \r\n    if (frozen) return;\r\n\r\n    let unobserve: (() => void) | undefined;\r\n\r\n    const observer = new IntersectionObserver(\r\n      (entries: IntersectionObserverEntry[]): void => {\r\n        const thresholds = Array.isArray(observer.thresholds)\r\n          ? observer.thresholds\r\n          : [observer.thresholds];\r\n\r\n        entries.forEach((entry) => {\r\n          const isIntersecting =\r\n            entry.isIntersecting &&\r\n            thresholds.some(\r\n              (threshold) => entry.intersectionRatio >= threshold,\r\n            );\r\n\r\n          setState({ isIntersecting, entry });\r\n\r\n          if (callbackRef.current) {\r\n            callbackRef.current(isIntersecting, entry);\r\n          }\r\n\r\n          if (isIntersecting && freezeOnceVisible && unobserve) {\r\n            unobserve();\r\n            unobserve = undefined;\r\n          }\r\n        });\r\n      },\r\n      { threshold, root, rootMargin },\r\n    );\r\n\r\n    observer.observe(ref);\r\n\r\n    return () => {\r\n      observer.disconnect();\r\n    };\r\n\r\n    \r\n  }, [\r\n    ref,\r\n    \r\n    JSON.stringify(threshold),\r\n    root,\r\n    rootMargin,\r\n    frozen,\r\n    freezeOnceVisible,\r\n  ]);\r\n\r\n  \r\n  const prevRef = useRef<Element | null>(null);\r\n\r\n  useEffect(() => {\r\n    if (\r\n      !ref &&\r\n      state.entry?.target &&\r\n      !freezeOnceVisible &&\r\n      !frozen &&\r\n      prevRef.current !== state.entry.target\r\n    ) {\r\n      prevRef.current = state.entry.target;\r\n      setState({ isIntersecting: initialIsIntersecting, entry: undefined });\r\n    }\r\n  }, [ref, state.entry, freezeOnceVisible, frozen, initialIsIntersecting]);\r\n\r\n  const result = [\r\n    setRef,\r\n    !!state.isIntersecting,\r\n    state.entry,\r\n  ] as IntersectionReturn;\r\n\r\n  \r\n  result.ref = result[0];\r\n  result.isIntersecting = result[1];\r\n  result.entry = result[2];\r\n\r\n  return result;\r\n}",
    "js": "import { useEffect, useRef, useState } from \"react\";\nexport function useIntersectionObserver({ threshold = 0, root = null, rootMargin = \"0%\", freezeOnceVisible = false, initialIsIntersecting = false, onChange, } = {}) {\n    const [ref, setRef] = useState(null);\n    const [state, setState] = useState(() => ({\n        isIntersecting: initialIsIntersecting,\n        entry: undefined,\n    }));\n    const callbackRef = useRef();\n    callbackRef.current = onChange;\n    const frozen = state.entry?.isIntersecting && freezeOnceVisible;\n    useEffect(() => {\n        if (!ref)\n            return;\n        if (!(\"IntersectionObserver\" in window))\n            return;\n        if (frozen)\n            return;\n        let unobserve;\n        const observer = new IntersectionObserver((entries) => {\n            const thresholds = Array.isArray(observer.thresholds)\n                ? observer.thresholds\n                : [observer.thresholds];\n            entries.forEach((entry) => {\n                const isIntersecting = entry.isIntersecting &&\n                    thresholds.some((threshold) => entry.intersectionRatio >= threshold);\n                setState({ isIntersecting, entry });\n                if (callbackRef.current) {\n                    callbackRef.current(isIntersecting, entry);\n                }\n                if (isIntersecting && freezeOnceVisible && unobserve) {\n                    unobserve();\n                    unobserve = undefined;\n                }\n            });\n        }, { threshold, root, rootMargin });\n        observer.observe(ref);\n        return () => {\n            observer.disconnect();\n        };\n    }, [\n        ref,\n        JSON.stringify(threshold),\n        root,\n        rootMargin,\n        frozen,\n        freezeOnceVisible,\n    ]);\n    const prevRef = useRef(null);\n    useEffect(() => {\n        if (!ref &&\n            state.entry?.target &&\n            !freezeOnceVisible &&\n            !frozen &&\n            prevRef.current !== state.entry.target) {\n            prevRef.current = state.entry.target;\n            setState({ isIntersecting: initialIsIntersecting, entry: undefined });\n        }\n    }, [ref, state.entry, freezeOnceVisible, frozen, initialIsIntersecting]);\n    const result = [\n        setRef,\n        !!state.isIntersecting,\n        state.entry,\n    ];\n    result.ref = result[0];\n    result.isIntersecting = result[1];\n    result.entry = result[2];\n    return result;\n}"
  }
}

=== sseuniverse/sse-hooks/packages/hooks/src/useMap/meta.json
{
  "$schema": "https://raw.githubusercontent.com/sseuniverse/sse-hooks/refs/heads/main/schema/meta.json",
  "name": "use-map",
  "type": "registry:hook",
  "title": "useMap",
  "description": "Represents the type for either a Map or an array of key-value pairs.",
  "dependencies": [
    "react"
  ],
  "registryDependencies": [],
  "file": {
    "content": "import { useCallback, useState } from \"react\";\r\n\r\n\r\ntype MapOrEntries<K, V> = Map<K, V> | [K, V][];\r\n\r\n\r\ntype UseMapActions<K, V> = {\r\n  \r\n  set: (key: K, value: V) => void;\r\n  \r\n  setAll: (entries: MapOrEntries<K, V>) => void;\r\n  \r\n  remove: (key: K) => void;\r\n  \r\n  reset: Map<K, V>[\"clear\"];\r\n};\r\n\r\n\r\ntype UseMapReturn<K, V> = [\r\n  Omit<Map<K, V>, \"set\" | \"clear\" | \"delete\">,\r\n  UseMapActions<K, V>,\r\n];\r\n\r\n\r\nexport function useMap<K, V>(\r\n  initialState: MapOrEntries<K, V> = new Map(),\r\n): UseMapReturn<K, V> {\r\n  const [map, setMap] = useState(new Map(initialState));\r\n\r\n  const actions: UseMapActions<K, V> = {\r\n    set: useCallback((key, value) => {\r\n      setMap((prev) => {\r\n        const copy = new Map(prev);\r\n        copy.set(key, value);\r\n        return copy;\r\n      });\r\n    }, []),\r\n\r\n    setAll: useCallback((entries) => {\r\n      setMap(() => new Map(entries));\r\n    }, []),\r\n\r\n    remove: useCallback((key) => {\r\n      setMap((prev) => {\r\n        const copy = new Map(prev);\r\n        copy.delete(key);\r\n        return copy;\r\n      });\r\n    }, []),\r\n\r\n    reset: useCallback(() => {\r\n      setMap(() => new Map());\r\n    }, []),\r\n  };\r\n\r\n  return [map, actions];\r\n}",
    "js": "import { useCallback, useState } from \"react\";\nexport function useMap(initialState = new Map()) {\n    const [map, setMap] = useState(new Map(initialState));\n    const actions = {\n        set: useCallback((key, value) => {\n            setMap((prev) => {\n                const copy = new Map(prev);\n                copy.set(key, value);\n                return copy;\n            });\n        }, []),\n        setAll: useCallback((entries) => {\n            setMap(() => new Map(entries));\n        }, []),\n        remove: useCallback((key) => {\n            setMap((prev) => {\n                const copy = new Map(prev);\n                copy.delete(key);\n                return copy;\n            });\n        }, []),\n        reset: useCallback(() => {\n            setMap(() => new Map());\n        }, []),\n    };\n    return [map, actions];\n}"
  }
}

=== sseuniverse/sse-hooks/packages/hooks/src/useBreakpoint/meta.json
{
  "$schema": "https://raw.githubusercontent.com/sseuniverse/sse-hooks/refs/heads/main/schema/meta.json",
  "name": "use-breakpoint",
  "type": "registry:hook",
  "title": "useBreakpoint",
  "description": "Breakpoints from Tailwind V2",
  "dependencies": [],
  "registryDependencies": [
    "use-media-query"
  ],
  "file": {
    "content": "export const breakpointsTailwind = {\n  sm: 640,\n  md: 768,\n  lg: 1024,\n  xl: 1280,\n  \"2xl\": 1536,\n};\n\nexport const breakpointsBootstrapV5 = {\n  sm: 576,\n  md: 768,\n  lg: 992,\n  xl: 1200,\n  xxl: 1400,\n};\n\nexport const breakpointsVuetify = {\n  xs: 600,\n  sm: 960,\n  md: 1264,\n  lg: 1904,\n};\n\nexport const breakpointsAntDesign = {\n  xs: 480,\n  sm: 576,\n  md: 768,\n  lg: 992,\n  xl: 1200,\n  xxl: 1600,\n};\n\nexport const breakpointsSematic = {\n  mobileS: 320,\n  mobileM: 375,\n  mobileL: 425,\n  tablet: 768,\n  laptop: 1024,\n  laptopL: 1440,\n  desktop4K: 2560,\n};\n\nimport { useMediaQuery } from \"./use-media-query\";\n\nfunction match(query: string): boolean {\n  if (typeof window === \"undefined\") return false;\n\n  return window.matchMedia(query).matches;\n}\n\nexport function useBreakpoint<\n  BreakPoints extends Record<string, number>,\n  BreakPointsKey extends keyof BreakPoints = keyof BreakPoints,\n>(breakpoints: BreakPoints) {\n  return {\n    useGreater: (k: BreakPointsKey) => {\n      return useMediaQuery(`(min-width: ${breakpoints[k]}px)`);\n    },\n\n    useSmaller: (k: BreakPointsKey) => {\n      return useMediaQuery(`(max-width: ${breakpoints[k]}px)`);\n    },\n\n    useBetween: (a: BreakPointsKey, b: BreakPointsKey) => {\n      return useMediaQuery(\n        `(min-width: ${breakpoints[a]}px) and (max-width: ${breakpoints[b]}px)`,\n      );\n    },\n\n    isGreater(k: BreakPointsKey) {\n      return match(`(min-width: ${breakpoints[k]}px)`);\n    },\n\n    isSmaller(k: BreakPointsKey) {\n      return match(`(max-width: ${breakpoints[k]}px)`);\n    },\n\n    isInBetween(a: BreakPointsKey, b: BreakPointsKey) {\n      return match(\n        `(min-width: ${breakpoints[a]}px) and (max-width: ${breakpoints[b]}px)`,\n      );\n    },\n  };\n}\n",
    "js": "export const breakpointsTailwind = {\n    sm: 640,\n    md: 768,\n    lg: 1024,\n    xl: 1280,\n    \"2xl\": 1536,\n};\nexport const breakpointsBootstrapV5 = {\n    sm: 576,\n    md: 768,\n    lg: 992,\n    xl: 1200,\n    xxl: 1400,\n};\nexport const breakpointsVuetify = {\n    xs: 600,\n    sm: 960,\n    md: 1264,\n    lg: 1904,\n};\nexport const breakpointsAntDesign = {\n    xs: 480,\n    sm: 576,\n    md: 768,\n    lg: 992,\n    xl: 1200,\n    xxl: 1600,\n};\nexport const breakpointsSematic = {\n    mobileS: 320,\n    mobileM: 375,\n    mobileL: 425,\n    tablet: 768,\n    laptop: 1024,\n    laptopL: 1440,\n    desktop4K: 2560,\n};\nimport { useMediaQuery } from \"./use-media-query\";\nfunction match(query) {\n    if (typeof window === \"undefined\")\n        return false;\n    return window.matchMedia(query).matches;\n}\nexport function useBreakpoint(breakpoints) {\n    return {\n        useGreater: (k) => {\n            return useMediaQuery(`(min-width: ${breakpoints[k]}px)`);\n        },\n        useSmaller: (k) => {\n            return useMediaQuery(`(max-width: ${breakpoints[k]}px)`);\n        },\n        useBetween: (a, b) => {\n            return useMediaQuery(`(min-width: ${breakpoints[a]}px) and (max-width: ${breakpoints[b]}px)`);\n        },\n        isGreater(k) {\n            return match(`(min-width: ${breakpoints[k]}px)`);\n        },\n        isSmaller(k) {\n            return match(`(max-width: ${breakpoints[k]}px)`);\n        },\n        isInBetween(a, b) {\n            return match(`(min-width: ${breakpoints[a]}px) and (max-width: ${breakpoints[b]}px)`);\n        },\n    };\n}"
  }
}

=== sseuniverse/sse-hooks/packages/hooks/src/useScreen/meta.json
{
  "$schema": "https://raw.githubusercontent.com/sseuniverse/sse-hooks/refs/heads/main/schema/meta.json",
  "name": "use-screen",
  "type": "registry:hook",
  "title": "useScreen",
  "description": "The hooks options.",
  "dependencies": [
    "react"
  ],
  "registryDependencies": [
    "use-debounce-callback",
    "use-event-listener",
    "use-isomorphic-layout-effect"
  ],
  "file": {
    "content": "import { useState } from \"react\";\r\n\r\n\n\n\n\r\ntype UseScreenOptions<InitializeWithValue extends boolean | undefined> = {\r\n  \r\n  initializeWithValue: InitializeWithValue;\r\n  \r\n  debounceDelay?: number;\r\n};\r\n\r\nconst IS_SERVER = typeof window === \"undefined\";\r\n\r\n\r\nexport function useScreen(options: UseScreenOptions<false>): Screen | undefined;\r\n\r\nexport function useScreen(options?: Partial<UseScreenOptions<true>>): Screen;\r\n\r\nexport function useScreen(\r\n  options: Partial<UseScreenOptions<boolean>> = {},\r\n): Screen | undefined {\r\n  let { initializeWithValue = true } = options;\r\n  if (IS_SERVER) {\r\n    initializeWithValue = false;\r\n  }\r\n\r\n  const readScreen = () => {\r\n    if (IS_SERVER) {\r\n      return undefined;\r\n    }\r\n    return window.screen;\r\n  };\r\n\r\n  const [screen, setScreen] = useState<Screen | undefined>(() => {\r\n    if (initializeWithValue) {\r\n      return readScreen();\r\n    }\r\n    return undefined;\r\n  });\r\n\r\n  const debouncedSetScreen = useDebounceCallback(\r\n    setScreen,\r\n    options.debounceDelay,\r\n  );\r\n\r\n  \r\n  function handleSize() {\r\n    const newScreen = readScreen();\r\n    const setSize = options.debounceDelay ? debouncedSetScreen : setScreen;\r\n\r\n    if (newScreen) {\r\n      \r\n      const {\r\n        width,\r\n        height,\r\n        availHeight,\r\n        availWidth,\r\n        colorDepth,\r\n        orientation,\r\n        pixelDepth,\r\n      } = newScreen;\r\n\r\n      setSize({\r\n        width,\r\n        height,\r\n        availHeight,\r\n        availWidth,\r\n        colorDepth,\r\n        orientation,\r\n        pixelDepth,\r\n      });\r\n    }\r\n  }\r\n\r\n  useEventListener(\"resize\", handleSize);\r\n\r\n  \r\n  useIsomorphicLayoutEffect(() => {\r\n    handleSize();\r\n  }, []);\r\n\r\n  return screen;\r\n}",
    "js": "import { useState } from \"react\";\nconst IS_SERVER = typeof window === \"undefined\";\nexport function useScreen(options = {}) {\n    let { initializeWithValue = true } = options;\n    if (IS_SERVER) {\n        initializeWithValue = false;\n    }\n    const readScreen = () => {\n        if (IS_SERVER) {\n            return undefined;\n        }\n        return window.screen;\n    };\n    const [screen, setScreen] = useState(() => {\n        if (initializeWithValue) {\n            return readScreen();\n        }\n        return undefined;\n    });\n    const debouncedSetScreen = useDebounceCallback(setScreen, options.debounceDelay);\n    function handleSize() {\n        const newScreen = readScreen();\n        const setSize = options.debounceDelay ? debouncedSetScreen : setScreen;\n        if (newScreen) {\n            const { width, height, availHeight, availWidth, colorDepth, orientation, pixelDepth, } = newScreen;\n            setSize({\n                width,\n                height,\n                availHeight,\n                availWidth,\n                colorDepth,\n                orientation,\n                pixelDepth,\n            });\n        }\n    }\n    useEventListener(\"resize\", handleSize);\n    useIsomorphicLayoutEffect(() => {\n        handleSize();\n    }, []);\n    return screen;\n}"
  }
}

=== sseuniverse/sse-hooks/packages/hooks/src/useCountdown/meta.json
{
  "$schema": "https://raw.githubusercontent.com/sseuniverse/sse-hooks/refs/heads/main/schema/meta.json",
  "name": "use-countdown",
  "type": "registry:hook",
  "title": "useCountdown",
  "description": "The countdown's options.",
  "dependencies": [
    "react"
  ],
  "registryDependencies": [
    "use-counter",
    "use-boolean",
    "use-interval"
  ],
  "file": {
    "content": "import { useCallback } from \"react\";\r\n\n\n\n\r\ntype CountdownOptions = {\r\n  \r\n  countStart: number;\r\n\r\n  \r\n  intervalMs?: number;\r\n  \r\n  isIncrement?: boolean;\r\n\r\n  \r\n  countStop?: number;\r\n};\r\n\r\n\r\ntype CountdownControllers = {\r\n  \r\n  startCountdown: () => void;\r\n  \r\n  stopCountdown: () => void;\r\n  \r\n  resetCountdown: () => void;\r\n};\r\n\r\n\r\n\r\nexport function useCountdown({\r\n  countStart,\r\n  countStop = 0,\r\n  intervalMs = 1000,\r\n  isIncrement = false,\r\n}: CountdownOptions): [number, CountdownControllers] {\r\n  const {\r\n    count,\r\n    increment,\r\n    decrement,\r\n    reset: resetCounter,\r\n  } = useCounter(countStart);\r\n\r\n  \r\n  const {\r\n    value: isCountdownRunning,\r\n    setTrue: startCountdown,\r\n    setFalse: stopCountdown,\r\n  } = useBoolean(false);\r\n\r\n  \r\n  const resetCountdown = useCallback(() => {\r\n    stopCountdown();\r\n    resetCounter();\r\n  }, [stopCountdown, resetCounter]);\r\n\r\n  const countdownCallback = useCallback(() => {\r\n    if (count === countStop) {\r\n      stopCountdown();\r\n      return;\r\n    }\r\n\r\n    if (isIncrement) {\r\n      increment();\r\n    } else {\r\n      decrement();\r\n    }\r\n  }, [count, countStop, decrement, increment, isIncrement, stopCountdown]);\r\n\r\n  useInterval(countdownCallback, isCountdownRunning ? intervalMs : null);\r\n\r\n  return [count, { startCountdown, stopCountdown, resetCountdown }];\r\n}",
    "js": "import { useCallback } from \"react\";\nexport function useCountdown({ countStart, countStop = 0, intervalMs = 1000, isIncrement = false, }) {\n    const { count, increment, decrement, reset: resetCounter, } = useCounter(countStart);\n    const { value: isCountdownRunning, setTrue: startCountdown, setFalse: stopCountdown, } = useBoolean(false);\n    const resetCountdown = useCallback(() => {\n        stopCountdown();\n        resetCounter();\n    }, [stopCountdown, resetCounter]);\n    const countdownCallback = useCallback(() => {\n        if (count === countStop) {\n            stopCountdown();\n            return;\n        }\n        if (isIncrement) {\n            increment();\n        }\n        else {\n            decrement();\n        }\n    }, [count, countStop, decrement, increment, isIncrement, stopCountdown]);\n    useInterval(countdownCallback, isCountdownRunning ? intervalMs : null);\n    return [count, { startCountdown, stopCountdown, resetCountdown }];\n}"
  }
}

=== sseuniverse/sse-hooks/packages/hooks/src/useUnmount/meta.json
{
  "$schema": "https://sse-hooks.vercel.app/api/registry/schema/hook.json",
  "name": "use-unmount",
  "type": "registry:hook",
  "title": "useUnmount",
  "description": "Custom hook that runs a cleanup function when the component is unmounted. ```tsx useUnmount(() => {   // Cleanup logic here }); ```",
  "dependencies": [
    "react"
  ],
  "registryDependencies": [],
  "file": {
    "content": "import { useEffect, useRef } from \"react\";\n\nexport function useUnmount(func: () => void) {\n  const funcRef = useRef(func);\n\n  funcRef.current = func;\n\n  useEffect(\n    () => () => {\n      funcRef.current();\n    },\n    [],\n  );\n}\n",
    "js": "import { useEffect, useRef } from \"react\";\nexport function useUnmount(func) {\n    const funcRef = useRef(func);\n    funcRef.current = func;\n    useEffect(() => () => {\n        funcRef.current();\n    }, []);\n}"
  }
}

=== sseuniverse/sse-hooks/packages/hooks/src/useForkRef/meta.json
{
  "$schema": "https://sse-hooks.vercel.app/api/registry/schema/hook.json",
  "name": "use-fork-ref",
  "type": "registry:hook",
  "title": "useForkRef",
  "description": "Merges refs into a single memoized callback ref or `null`. ```tsx const rootRef = React.useRef<Instance>(null); const refFork = useForkRef(rootRef, props.ref); return (   <Root {...props} ref={refFork} /> ); ```",
  "dependencies": [
    "react"
  ],
  "registryDependencies": [],
  "file": {
    "content": "import React from \"react\";\n\nexport function useForkRef<Instance>(\n  ...refs: Array<React.Ref<Instance> | undefined>\n): React.RefCallback<Instance> | null {\n  const cleanupRef = React.useRef<() => void>(undefined);\n\n  const refEffect = React.useCallback((instance: Instance) => {\n    const cleanups = refs.map((ref) => {\n      if (ref == null) {\n        return null;\n      }\n\n      if (typeof ref === \"function\") {\n        const refCallback = ref;\n        const refCleanup: void | (() => void) = refCallback(instance);\n        return typeof refCleanup === \"function\"\n          ? refCleanup\n          : () => {\n              refCallback(null);\n            };\n      }\n\n      ref.current = instance;\n      return () => {\n        ref.current = null;\n      };\n    });\n\n    return () => {\n      cleanups.forEach((refCleanup) => refCleanup?.());\n    };\n  }, refs);\n\n  return React.useMemo(() => {\n    if (refs.every((ref) => ref == null)) {\n      return null;\n    }\n\n    return (value) => {\n      if (cleanupRef.current) {\n        cleanupRef.current();\n        cleanupRef.current = undefined;\n      }\n\n      if (value != null) {\n        cleanupRef.current = refEffect(value);\n      }\n    };\n  }, refs);\n}\n",
    "js": "import React from \"react\";\nexport function useForkRef(...refs) {\n    const cleanupRef = React.useRef(undefined);\n    const refEffect = React.useCallback((instance) => {\n        const cleanups = refs.map((ref) => {\n            if (ref == null) {\n                return null;\n            }\n            if (typeof ref === \"function\") {\n                const refCallback = ref;\n                const refCleanup = refCallback(instance);\n                return typeof refCleanup === \"function\"\n                    ? refCleanup\n                    : () => {\n                        refCallback(null);\n                    };\n            }\n            ref.current = instance;\n            return () => {\n                ref.current = null;\n            };\n        });\n        return () => {\n            cleanups.forEach((refCleanup) => refCleanup?.());\n        };\n    }, refs);\n    return React.useMemo(() => {\n        if (refs.every((ref) => ref == null)) {\n            return null;\n        }\n        return (value) => {\n            if (cleanupRef.current) {\n                cleanupRef.current();\n                cleanupRef.current = undefined;\n            }\n            if (value != null) {\n                cleanupRef.current = refEffect(value);\n            }\n        };\n    }, refs);\n}"
  }
}
